services:
  php-apache-environment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./app/:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql